apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: NodePort
  selector:
    app: demo-python-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30005
